```{r echo=FALSE, results="asis"}
if (!exists("INCLUDE_CHILD_HEADER") || isTRUE(INCLUDE_CHILD_HEADER)) {
	cat("# Usage in R Markdown")
}
```

Panelset works in all R Markdown HTML outputs
like HTML reports and [blogdown](https://bookdown.org/yihui/blogdown/) webpages!

Panelset works in the same way as
`rmarkdown`'s [tabset](https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html) feature,
albeit with fewer style options,
but the trade-off is that it works in a wider range of document types.
Generally, as long as the output is HTML, panelset should work.

Another advantage of panelset is that it enables deeplinking:
the currently shown tab is encoded in the URL automatically,
allowing users to link to open tabs.
Users can also right click on a panel's tab
and select _Copy Link_ to link directly to a specific panel's tab,
which will appear in view when visiting the copied link.

With standard R Markdown, i.e. [rmarkdown::html_document()], 
you can use the following template.

```markdown
# Panelset In R Markdown! {.panelset}

## Tab One

Amet enim aptent molestie vulputate pharetra
vulputate primis et vivamus semper.

## Tab Two

### Sub heading one

Sit etiam malesuada arcu fusce ullamcorper
interdum proin tincidunt curabitur felis?

## Tab Three

Adipiscing mauris egestas vitae pretium 
ad dignissim dictumst platea!

# Another section

This content won't appear in a panel.
```

In other, 
less-standard R Markdown HTML formats,
you can use pandoc's [fenced divs](https://pandoc.org/MANUAL.html#extension-fenced_divs).

````markdown
::::: {.panelset}

::: {.panel}
[First Tab]{.panel-name}

Lorem sed non habitasse nulla donec egestas magna
enim posuere fames ante diam!
:::

::: {.panel}
[Second Tab]{.panel-name}

Consectetur ligula taciti neque scelerisque gravida
class pharetra netus lobortis quisque mollis iaculis.
:::

:::::
````

Alternatively, you can also use raw HTML.

````html
<div class="panelset">
  <div class="panel">
    <div class="panel-name">First Tab</div>
    <!-- Panel content -->
    <p>Lorem ipsum, etc, etc</p>
  </div>
  <div class="panel">
    <div class="panel-name">Second Tab</div>
    <!-- Panel content -->
    <p>Lorem ipsum, etc, etc</p>
  </div>
</div>
````
